### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [ValerijBel/Infostart_1199_FinalTask#10]
В комментарии к этому issue напишите ваши:

* Имя Фамилию (в дательном падеже)
* Адрес электронной почты, на которую выслать сертификат

**Comment by ValerijBel** [comment]
Валерию Белоцерковникову
valerij.bel@gmail.com

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by ValerijBel** [comment]
Письмо получил, спасибо!

**Comment by alehinsasha** [comment]
Успехов Валерий! Вы большой молодец!..
