### ISSUE TITLE
Демонстрация работ заказчику

### ISSUE THREAD

**Issue by alehinsasha** [ValerijBel/Infostart_1199_FinalTask#5]
**Что нужно сделать**

1. Выгрузить конфигурацию в файлы (конфигуратор → конфигурация → выгрузить конфигурацию в файлы → <ИмяРепозиторияФинальногоЗадания>\src\cf);
2. Закоммитить и отправить во внешний репозиторий.

**Особенности**

* Приступать к выполнению этой задачи нужно после того как закроете все созданные мной issue.
* В публичный внешний репозиторий, нельзя помещать код из типовых конфигураций 1С!

**Comment by alehinsasha** [comment]
В cf должны лежать исходники, а не бинарь *.cf

> Выгрузить конфигурацию в файлы (конфигуратор → конфигурация → выгрузить конфигурацию в файлы → <ИмяРепозиторияФинальногоЗадания>\src\cf);

Помните об этом, я сейчас не буду придераться)

**Comment by ValerijBel** [comment]
Каюсь, трижды прочитал "что нужно сделать" и не заметил самого главного.

**Comment by alehinsasha** [comment]
Дело привычки, как и номер issue в описании коммита.
